# Generated by Django 4.2.2 on 2024-02-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kmsd", "0002_attendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="datetime",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="presence",
        ),
        migrations.AddField(
            model_name="attendance",
            name="present_days",
            field=models.IntegerField(default=0),
        ),
    ]
