# Generated by Django 4.2.2 on 2024-02-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kmsd", "0003_remove_attendance_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="grade",
            field=models.IntegerField(default=0),
        ),
    ]
